### ISSUE TITLE
Error schema max header size error

### ISSUE THREAD

**Issue by sindile** [pelias/schema#348]
I seem to be hitting this error https://github.com/pelias/schema/issues/343

This is the output of pelias elastic create with the South Africa project. I can confirm I am using image: pelias/schema:master
error: [schema] Max header size is below 16384 bytes. Be sure to use the provided wrapper script in './bin' rather than calling this script directly.Otherwise, you may experience issues when using Elasticsearch 5.See https://github.com/pelias/schema#compatibility for more details.

**Comment by missinglink** [comment]
Hi @sindile 

I believe this issue was fixed in https://github.com/pelias/docker/pull/66 on Jan 23rd.
It's possible that your version of `pelias/docker` is out-of-date.

Please run `pelias system update` to update it and try again.

**Comment by sindile** [comment]
Hi @missinglink 
Even after running pelias system update and also cloning a new repository I am still getting the same error.

**Comment by orangejulius** [comment]
Hello @sindile!

This might be caused by an out of date Docker image. On my system I see the following:

```
julian@manhattan ~/repos/pelias/docker/projects/south-africa $ docker image ls pelias/schema:master
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
pelias/schema       master              e91ac54a49fb        13 days ago         505MB
```

Can you confirm you have the same image id? If not, a `pelias compose pull` should update to the latest one.

**Comment by sindile** [comment]
Hello @orangejulius 

I have the same image
sindile@sxjlpt:~ $ docker image ls pelias/schema:master
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
pelias/schema       master              e91ac54a49fb        2 weeks ago         505MB

**Comment by orangejulius** [comment]
We've fixed the underlying issue that required these warnings and errors, and it's merged into the schema project as of https://github.com/pelias/schema/pull/372.

With updated docker images this definitely should not be an issue any more.

If anyone is still seeing errors like this please let us know.
